### ISSUE TITLE
你好，我最近也在学习这个，请问您的代码截至目前功能都正常么？

### ISSUE THREAD

**Issue by wojiaojinshuaiyu** [ian688t6/qtscrcpy#1]

**Comment by ian688t6** [comment]
你好啊 目前没遇到什么问题

**Comment by wojiaojinshuaiyu** [comment]
嗯，谢谢，我代码也调好了，我的问题是没用他提供的server.jar,我目前还没看完，我不确定他后面会不会更正，目前我是发现这个老师有一个地方可能不对，他在union结构中对textevent中使用QSTring，我查了一下，union中好像不能使用QString
